name: portfolio
description: "The personal portfolio of Tawfiqur Rahman"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  responsive_framework: ^1.1.1
  animate_do: ^3.1.2
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
